SERVER_PORT: 8095
DATASOURCE_PORT: 5435
DATASOURCE_DATABASE: catalog_service
DATASOURCE_USERNAME: admin
DATASOURCE_PASSWORD: password
DATASOURCE_HOST: localhost
DATASOURCE_HOST_DB_DRIVER: postgresql

DATASOURCE_URL: ${DATASOURCE_HOST_DB_DRIVER}://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}

FLYWAY_DATASOURCE_URL: jdbc:${DATASOURCE_URL}
R2DBC_DATASOURCE_URL: r2dbc:${DATASOURCE_URL}

ELASTICSEARCH_REACTIVE_CLIENT_ENDPOINTS: http://localhost:9200
ELASTICSEARCH_REACTIVE_CLIENT_USERNAME: elastic
ELASTICSEARCH_REACTIVE_CLIENT_PASSWORD: password


logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
    io:
      eventuate: DEBUG