SERVER_PORT: 8095
DATASOURCE_PORT: 5435
DATASOURCE_DATABASE: catalog_service
DATASOURCE_USERNAME: admin
DATASOURCE_PASSWORD: password
DATASOURCE_HOST: localhost
DATASOURCE_HOST_DB_DRIVER: postgresql

DATASOURCE_URL: ${DATASOURCE_HOST_DB_DRIVER}://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}

FLYWAY_DATASOURCE_URL: jdbc:${DATASOURCE_URL}
R2DBC_DATASOURCE_URL: r2dbc:${DATASOURCE_URL}

ELASTICSEARCH_REACTIVE_CLIENT_ENDPOINTS: http://localhost:9200
ELASTICSEARCH_REACTIVE_CLIENT_USERNAME: elastic
ELASTICSEARCH_REACTIVE_CLIENT_PASSWORD: password


logging:
  level:
    reactor.netty.channel.ChannelOperationsHandler: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty.handler: DEBUG
    io.netty.handler.proxy.HttpProxyHandler: DEBUG
    io.netty.handler.proxy.ProxyHandler: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.channel: DEBUG
    org.springframework.orm.jpa: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    io.eventuate: DEBUG