DATASOURCE_PORT: 5432
DATASOURCE_DATABASE: catalog_service
DATASOURCE_USERNAME: admin
DATASOURCE_PASSWORD: password
DATASOURCE_HOST: catalog-service-postgres
DATASOURCE_HOST_DB_DRIVER: postgresql

ELASTICSEARCH_REACTIVE_CLIENT_ENDPOINTS: http://catalog-service-elasticsearch:9200
ELASTICSEARCH_REACTIVE_CLIENT_USERNAME: elastic
ELASTICSEARCH_REACTIVE_CLIENT_PASSWORD: password

DATASOURCE_URL: ${DATASOURCE_HOST_DB_DRIVER}://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}

FLYWAY_DATASOURCE_URL: jdbc:${DATASOURCE_URL}
R2DBC_DATASOURCE_URL: r2dbc:${DATASOURCE_URL}

EVENTUATE_KAFKA_BOOTSTRAP_SERVERS: http://kafka:29092
EVENTUATE_ZOOKEEPER_URL: http://zookeeper:2181

OAUTH2_JWK_SET_URI: http://keycloak:8080/realms/food-ordering-app/protocol/openid-connect/certs