food-ordering-app:
  service:
    port: 80
    type: ClusterIP
  ingress:
    enabled: true
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://34.116.174.157:8080"  # Change this to your Keycloak URL
      REACT_API_GATEWAY_URL: "http://api-gw.food-ordering-system.com" # Change this to your API GW URL

delivery-app:
  service:
    port: 80
    type: ClusterIP
  ingress:
    enabled: true
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://34.116.174.157:8080" # Change this to your Keycloak URL
      REACT_API_GATEWAY_URL: "http://api-gw.food-ordering-system.com" # Change this to your API GW URL

restaurant-app:
  service:
    port: 80
    type: ClusterIP
  ingress:
    enabled: true
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://34.116.174.157:8080" # Change this to your Keycloak URL
      REACT_API_GATEWAY_URL: "http://api-gw.food-ordering-system.com"

redis:
  volumePermissions:
    enabled: true
  fullnameOverride: redis
  auth:
    enabled: false
  #  password: password
  master:
    persistence:
      enabled: true
      size: 2Gi
  architecture: replication # or standalone might be enough
  replica:
    persistence:
      size: 2Gi
  metrics:
    enabled: true

zipkin:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce"
    host: ""

kube-prometheus-stack:
  grafana:
    adminPassword:
      password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "gce"
  prometheus:
    ingress:
      enabled: true
      paths:
        - /*
      annotations:
        kubernetes.io/ingress.class: "gce"
    prometheusSpec:
      externalUrl: ""
      additionalScrapeConfigs: |
        - job_name: 'prometheus'
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: 'order-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ["order-service:8080"]
              labels:
                application: 'Order service'
        - job_name: 'api-gateway-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['api-gateway:8080']
              labels:
                application: 'Api gateway'
        - job_name: 'restaurant-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['restaurant-service:8080']
              labels:
                application: 'Restaurant service'
        - job_name: 'payment-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['payment-service:8080']
              labels:
                application: 'Payment service'
        - job_name: 'kitchen-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['kitchen-service:8080']
              labels:
                application: 'Kitchen service'
        - job_name: 'delivery-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['delivery-service:8080']
              labels:
                application: 'Delivery service'
        - job_name: 'catalog-service-metrics'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['catalog-service:8080']
              labels:
                application: 'Catalog service'
