
export enum DeliveryStatus {
  WAITING_FOR_KITCHEN = "WAITING_FOR_KITCHEN",
  AT_DELIVERY = "AT_DELIVERY",
  DELIVERED = "DELIVERED",
}

export enum KitchenTicketStatus {
  PREPARING = "PREPARING",
  READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
  CANCELLED = "CANCELLED",
  FINISHED = "FINISHED"
}
