apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.service.name }}
    {{- with .Values.keycloak.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    role: {{ .Values.service.name }}