apiVersion: v2
name: restaurant-service
description: Restaurant service helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "0.0.2-SNAPSHOT"

dependencies:
  - name: postgresql
    version: "0.1.0"
    repository: "file://../postgres"