global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'order-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Order service'
  - job_name: 'api-gateway-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8070']
        labels:
          application: 'Api gateway'
  - job_name: 'restaurant-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          application: 'Restaurant service'
  - job_name: 'payment-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8090' ]
        labels:
          application: 'Payment service'
  - job_name: 'kitchen-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8088' ]
        labels:
          application: 'Kitchen service'
  - job_name: 'delivery-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8092' ]
        labels:
          application: 'Delivery service'
  - job_name: 'catalog-service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8095' ]
        labels:
          application: 'Catalog service'