server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver


