server:
  port: 8090

spring:
  application:
    name: payment-service
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:flyway/{vendor}
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_service
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000

eventuatelocal:
  kafka:
    bootstrap:
      servers: http://localhost:9092
  zookeeper:
    connection:
      string: http://localhost:2181

eventuate:
  database:
    schema: public

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
    io:
      eventuate: DEBUG