server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
  distributed:
    enabled: true
  #  eventhandling:
#    processors:
#      my-processor:
#        mode: tracking
#        thread-count: 4
#        initial-segment-count: 4
  axonserver:
    eventhandling:
      processors:
        my-processor:
          automatic-balancing: true
  kafka:
    bootstrap-servers: localhost:19092
    client-id: kafka-axon-example
    default-topic: local.event
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: transactional

    producer:
      bootstrap-servers: localhost:29092
      transaction-id-prefix: order-service
      retries: 3
      event-processor-mode: subscribing
      acks: all
      compression-type: snappy
      # For additional unnamed properties, add them to the `properties` map like so
#      properties:
#        some-key: [ some-value ]

    fetcher:
      poll-timeout: 3000

    consumer:
      bootstrap-servers: localhost:29092
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: subscribing
      # For additional unnamed properties, add them to the `properties` map like so
  eventhandling:
    processors:
      "[WalletProcessor]":
        source: kafkaMessageSource
        mode: subscribing
#      properties:
#        some-key: [ some-value ]
