server:
  port: 8080

spring:
  application:
    name: order-service
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:flyway/{vendor}
  jpa:
    generate-ddl: true
  #    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
  docker:
    compose:
      enabled: false
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
    io:
      eventuate: DEBUG

eventuatelocal:
  kafka:
    bootstrap:
      servers: http://localhost:9092
  zookeeper:
    connection:
      string: http://localhost:2181

eventuate:
  database:
    schema: public