apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.service.name }}
    {{- with .Values.elasticsearch.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  clusterIP: None
  selector:
    role: {{ .Values.service.name }}