apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name | default "postgres-pv"}}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: {{ printf "/tmp/postgres/%s" (.Values.persistentVolume.name | default "postgres-pv") }}