replicaCount: 1

image:
  repository: xmlynek/com.food.ordering.app.delivery-app
  tag: ""
  pullPolicy: Always

imagePullSecrets:
#  - name:

nameOverride: "delivery-app"
fullnameOverride: "delivery-app"

env:
  secret: {}
  normal:
    REACT_API_GATEWAY_URL: "http://localhost:8060"
    REACT_KEYCLOAK_URL: "http://localhost:8070"
    REACT_KEYCLOAK_REALM: "delivery"
    REACT_KEYCLOAK_CLIENT_ID: "delivery-client-app"
    REACT_DELIVERY_SERVICE_PATH: "/delivery-service/api/delivery"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 5175
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: "delivery-ingress-static-ip"
  hosts:
    - host: "delivery.food-ordering-system.com"
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
