apiVersion: v1
kind: Secret
metadata:
  name: food-ordering-app-secrets
  labels:
    {{- include "food-ordering-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
    {{ $key | nindent 2 }}: {{ $val | b64enc }}
    {{- end}}
