SERVER_PORT: 8085
GCP_CREDENTIALS_LOCATION: classpath:studied-stock-416418-461f4c74d687.json
GCP_STORAGE_PROJECT_ID: studied-stock-416418
GCP_STORAGE_BUCKET_NAME: food-ordering-app-media
DATASOURCE_URL: jdbc:postgresql://localhost:5434/restaurant_service

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
    io:
      eventuate: DEBUG