DATASOURCE_URL: jdbc:postgresql://restaurant-service-postgres:5432/restaurant_service
OAUTH2_JWK_SET_URI: http://keycloak:8080/realms/restaurant/protocol/openid-connect/certs
EVENTUATE_KAFKA_BOOTSTRAP_SERVERS: http://kafka:29092
EVENTUATE_ZOOKEEPER_URL: http://zookeeper:2181
GCP_STORAGE_URL: http://minio:9000