server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: delivery-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 360000
      cache-null-values: false
      key-prefix: ${spring.application.name}-cache-
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:flyway/{vendor}
  jpa:
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      initialization-fail-timeout: 30000
  thymeleaf:
    enabled: false

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    enabled: true
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.15}
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${EVENTUATE_KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
  zookeeper:
    connection:
      string: ${EVENTUATE_ZOOKEEPER_URL:http://localhost:2181}


eventuate:
  database:
    schema: ${EVENTUATE_DATABASE_SCHEMA:public}

app:
  properties:
    command:
      handler:
        channel: ${SAGA_COMMAND_HANDLER_CHANNEL:delivery-service}


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org:
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
      hibernate:
        SQL: WARN
    io:
      eventuate: WARN
