keycloak:
  service:
    port: 8070
    type: LoadBalancer

food-ordering-app:
  service:
    port: 5173
    type: LoadBalancer
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://localhost:8070"
      REACT_API_GATEWAY_URL: "http://localhost:8060"

restaurant-app:
  service:
    port: 5174
    type: LoadBalancer
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://localhost:8070"
      REACT_API_GATEWAY_URL: "http://localhost:8060"

delivery-app:
  service:
    port: 5175
    type: LoadBalancer
  env:
    normal:
      REACT_KEYCLOAK_URL: "http://localhost:8070"
      REACT_API_GATEWAY_URL: "http://localhost:8060"

catalog-service:
  service:
    port: 8085
    type: LoadBalancer
  env:
    normal:
      OAUTH2_JWK_SET_URI: "http://keycloak:8070/realms/food-ordering-app/protocol/openid-connect/certs"

delivery-service:
  service:
    port: 8084
    type: LoadBalancer
  env:
    normal:
      OAUTH2_JWK_SET_URI: "http://keycloak:8070/realms/delivery/protocol/openid-connect/certs"

kitchen-service:
  service:
    port: 8083
    type: LoadBalancer
  env:
    normal:
      OAUTH2_JWK_SET_URI: "http://keycloak:8070/realms/restaurant/protocol/openid-connect/certs"

payment-service:
  service:
    port: 8082
    type: LoadBalancer

restaurant-service:
  service:
    port: 8081
    type: LoadBalancer
  env:
    normal:
      OAUTH2_JWK_SET_URI: "http://keycloak:8070/realms/restaurant/protocol/openid-connect/certs"

order-service:
  service:
    port: 8080
    type: LoadBalancer
  env:
    normal:
      OAUTH2_JWK_SET_URI: "http://keycloak:8070/realms/food-ordering-app/protocol/openid-connect/certs"

api-gateway:
  service:
    port: 8060
    type: LoadBalancer
  env:
    normal:
      CATALOG_SERVICE_URI: http://catalog-service:8085
      DELIVERY_SERVICE_URI: http://delivery-service:8084
      KITCHEN_SERVICE_URI: http://kitchen-service:8083
      RESTAURANT_SERVICE_URI: http://restaurant-service:8081
      ORDER_SERVICE_URI: http://order-service:8080

redis:
  volumePermissions:
    enabled: true
  fullnameOverride: redis
  auth:
    enabled: false
  #  password: password
  master:
    persistence:
      enabled: true
      size: 2Gi
  architecture: replication # or standalone might be enough
  replica:
    persistence:
      size: 2Gi
  metrics:
    enabled: true